/**
 * The 2021 SVG asset corpus — generated by core/scripts/svg2ts.ts.
 * Do not edit by hand.
 *
 * These are the drawings the Origins video was made from, recovered
 * from the C4D preferences folder they lived in outside version
 * control (docs/reports/origins-vocabulary.md §4).
 */

export { amazonLogo } from "./amazon_logo"
export { appleLogo } from "./apple_logo"
export { cash } from "./cash"
export { control } from "./control"
export { cropTalk } from "./crop_talk"
export { david } from "./david"
export { dna } from "./dna"
export { dodecahedron } from "./dodecahedron"
export { education } from "./education"
export { emu } from "./emu"
export { factory } from "./factory"
export { fire } from "./fire"
export { gearBig } from "./gear_big"
export { gearSmall } from "./gear_small"
export { github } from "./github"
export { googleLogo } from "./google_logo"
export { headFront } from "./head_front"
export { headSide } from "./head_side"
export { healthcare } from "./healthcare"
export { individual } from "./individual"
export { infinitySymbol } from "./infinity_symbol"
export { justice } from "./justice"
export { leftFoot } from "./left_foot"
export { man } from "./man"
export { microsoftLogo } from "./microsoft_logo"
export { rightEye } from "./right_eye"
export { rightFoot } from "./right_foot"
export { stethoscope } from "./stethoscope"
export { treeHighRes } from "./tree_high_res"
export { treeMediumRes } from "./tree_medium_res"
export { wave } from "./wave"
export { world } from "./world"
