/**
 * microsoft_logo — generated by core/scripts/svg2ts.ts. Do not edit by hand.
 *
 * Source: refs/pitch/svg-assets/svg/microsoft_logo.svg
 * SHA-256 (first 16): db93e9ebc9f63570
 * 4 subpaths, 20 points, centered, y-flipped,
 * in the SVG's own units (scale to a height via the Sketch's `height`).
 */

import type { SketchData } from "../data"

export const microsoftLogo: SketchData = {
  name: "microsoft_logo",
  source: "refs/pitch/svg-assets/svg/microsoft_logo.svg",
  hash: "db93e9ebc9f63570",
  subpaths: [
    [-127,-127, -127,-6.047, -6.047,-6.047, -6.047,-127, -127,-127],
    [6.047,-127, 6.047,-6.047, 127,-6.047, 127,-127, 6.047,-127],
    [-127,6.047, -127,127, -6.047,127, -6.047,6.047, -127,6.047],
    [6.047,6.047, 6.047,127, 127,127, 127,6.047, 6.047,6.047],
  ],
  closed: [1,1,1,1],
}
