/**
 * The PL02 deck's slide modules — generated by core/scripts/key2ts.ts.
 * Do not edit by hand.
 *
 * "Project Liminality" (2023-02-15), the 88-slide production deck that
 * IS the video — 100% Keynote, no pydeation, no footage
 * (docs/reports/pl02-vocabulary.md). Only slides 1-58 are in scope:
 * 59-83 are later additions that appear nowhere in the video.
 *
 * Emitted here: slide20, slide21, slide26, slide27, slide28, slide39, slide40, slide41, slide42.
 * The rest generate on demand — `bun core/scripts/key2ts.ts --slides N`.
 */

export { slide20 } from "./slide20"
export { slide21 } from "./slide21"
export { slide26 } from "./slide26"
export { slide27 } from "./slide27"
export { slide28 } from "./slide28"
export { slide39 } from "./slide39"
export { slide40 } from "./slide40"
export { slide41 } from "./slide41"
export { slide42 } from "./slide42"
