/**
 * The PL02 deck's slide modules — generated by core/scripts/key2ts.ts.
 * Do not edit by hand.
 *
 * "Project Liminality" (2023-02-15), the 88-slide production deck that
 * IS the video — 100% Keynote, no pydeation, no footage
 * (docs/reports/pl02-vocabulary.md). Only slides 1-58 are in scope:
 * 59-83 are later additions that appear nowhere in the video.
 *
 * Emitted here: slide01, slide02, slide03, slide04, slide05, slide06, slide19.
 * The rest generate on demand — `bun core/scripts/key2ts.ts --slides N`.
 */

export { slide01 } from "./slide01"
export { slide02 } from "./slide02"
export { slide03 } from "./slide03"
export { slide04 } from "./slide04"
export { slide05 } from "./slide05"
export { slide06 } from "./slide06"
export { slide19 } from "./slide19"
