/**
 * Globe — the world as a spinning, orthographically-projected sphere, drawn
 * either as filled continents or as coastline outlines.
 *
 * The recurring symbol of the Liminal Consulting Web3 video: it appears in
 * four of the seventeen shots (docs/reports/web3-recon.md, shots 1/3/13/15)
 * and carries the piece's whole yin-yang argument — the globe is the "world"
 * that Web2 centralises and Web3 decentralises. It earns holon status on
 * recurrence, and the modes decision (below) confirms it is ONE thing.
 *
 * THE MODES ARE ONE SPINE — the decision the recon flagged.
 *
 * Recon warned the globe's three "modes" might be "three different things
 * wearing one name". Looking at the frames, they are not. Every shot is the
 * SAME sphere: lon/lat coastlines projected orthographically, spun about the
 * pole, with the far face hidden. Only two things vary, and both are ordinary
 * parameters, not separate classes (DreamTalk's "abilities over classes"):
 *
 *   - `continents`: "fill" (shots 1/3/15 — Australia, Africa as solid shapes)
 *     vs "outline" (shot 13 — coastlines as white splines). ONE dataset, two
 *     treatments: filled rings are limb-clamped closed loops the even-odd fill
 *     floods; outlined rings are their near-face arcs, drawn as open strokes.
 *   - colour: a dark globe on black (shot 1), a bright globe (shots 3/15/13).
 *
 * What is NOT the globe: the red flower-of-life halo and light rays (shots
 * 3/15), and the hotspot + arc-network wrapping the sphere (shot 13). Those
 * are DECORATION composed AROUND the globe in a scene — the halo reuses the
 * existing flower packing (src/geometry/flower.ts hexPack), the rays and arcs
 * are a handful of lines. Folding them in would make three things wear one
 * name, exactly what recon feared; keeping them in the demo keeps the holon a
 * globe. See GlobeDemo.
 *
 * THE CONTINENTS ARE REAL DATA, NOT INVENTED.
 *
 * `continents.ts` is Natural Earth's ne_110m_land (public domain, the coarsest
 * standard land layer), generated by scripts/gen-globe-continents.ts — major
 * landmasses only, lightly simplified, stored as lon/lat degrees. This is the
 * least-invented convincing option the task asked for: a graticule alone reads
 * as "a sphere" but not as "the Earth" (shot 1 needs Australia recognisable),
 * and hand-tracing coastlines from 1280px frames would invent geography badly.
 * Not one coordinate is guessed. The projection is data-free, so the same
 * rings serve every face and every rotation.
 *
 * ONE PARAM DRIVES EVERYTHING: `spin`
 *
 * `spin` (radians) turns the globe about its pole. Every continent's geometry
 * is DERIVED from `spin` (and the fixed `tilt`) through the pure projection in
 * src/geometry/globe.ts — so the holon is a pure function of one number and
 * scrubs backwards exactly. Rotation is therefore a parameter to animate, not
 * a wall-clock effect: `globe.spin.to(TAU)` over N seconds turns it once.
 *
 * THE LIMB is the sphere's silhouette — a plain Circle of the globe's radius.
 * Its stroke is the thin ring outline that draws on in shot 1; its fill (when
 * the globe is a bright disc, shots 3/15/13-late) is the ocean the continents
 * sit on.
 */

import { Circle, Group, Line, Null, Stroke, type Vec3Like } from "../../src/parts/primitives"
import { bool, color, completion, length, scalar, angle } from "../../src/params"
import { type Color, rgb } from "../../src/constants"
import { clampedRing, frontArcs } from "../../src/geometry/globe"
import { continentRings } from "./continents"

/** The dark-globe grey of shot 1 (globe #333 on black). */
const DARK_LAND: Color = rgb(0x33, 0x33, 0x33)

export class Globe extends Null {
  /** ONTOLOGY.md: a sovereign symbol — cast, not asset. */
  static sovereign = true

  /** The sphere's radius in scene units — the drawn globe's size. */
  radius = length(200)

  /**
   * How the land reads. "fill" floods the continents (shots 1/3/15); "outline"
   * draws them as coastline strokes on a bare sphere (shot 13). A construction
   * choice — it decides which geometry each continent is built from — so it is
   * set once and not animated. To cross-fade the two, run two Globes.
   */
  continents: "fill" | "outline" = "fill"

  /**
   * Rotation about the pole, radians — THE param to animate. 0 faces the
   * prime meridian (Africa/Europe, the hero shot's face); increasing it spins
   * the globe eastward. Every continent's shape is a pure function of this.
   */
  spin = scalar(0)

  /**
   * Lean of the pole toward (+) or away (−) from the camera, radians. Fixed,
   * not animated: it sets the face's framing (shot 1's pole tips slightly
   * away). Small values keep the globe near dead-on.
   */
  tilt = angle(0.12)

  /** The land colour — dark on black (shot 1) or white (shots 3/15/13). */
  land = color(DARK_LAND)

  /**
   * The land's fill opacity in "fill" mode. Animate it if the continents
   * should flood on; the reference's are solid, so it defaults full. Ignored
   * in "outline" mode (there is no fill).
   */
  landOpacity = completion(1)

  /** Coastline stroke width in "outline" mode (shot 13's white splines). */
  coastStroke = length(3)

  /**
   * The limb — the sphere's silhouette circle, drawn as a stroke. This is the
   * thin ring outline that draws on in shot 1. Zero width (the default) leaves
   * the globe rimless, as the bright hero globes (shots 3/15) are — there the
   * black ocean against the black background needs no drawn edge.
   */
  limbStroke = length(0)
  limbTint = color(rgb(0x88, 0x88, 0x88))

  /**
   * The ocean disc under the continents — the limb's FILL, its own colour.
   * Off by default: the reference's globes are land-on-black (shot 1's grey
   * land, shots 3/15/13's white land) with a BLACK ocean, so no disc is drawn.
   * Set `oceanOpacity` for a coloured sea beneath outline coastlines.
   */
  oceanTint = color(rgb(0x11, 0x11, 0x11))
  oceanOpacity = completion(0)

  /** Draw the pole-to-pole / equator graticule faintly over the sphere. */
  graticule = bool(false)
  graticuleTint = color(rgb(0x55, 0x55, 0x55))
  /** Meridian and parallel counts when `graticule` is on. */
  meridians = length(12)
  parallels = length(6)

  ocean!: Circle
  limb!: Circle
  landHolon!: Stroke
  grid!: Group

  protected override compose(): void {
    // --- the ocean disc, then the limb ring -------------------------------
    // Two Circles rather than one, because the ocean wash and the silhouette
    // stroke carry INDEPENDENT colours (a grey ring over a dark sea) and a
    // Stroke's wash takes the shape's own tint. The ocean is added first so
    // the continents composite over it; the limb ring is added last so the
    // edge sits on top of everything.
    this.ocean = this.add(
      new Circle({
        radius: this.radius,
        tint: this.oceanTint,
        stroke: scalar(0),
        fillOpacity: this.oceanOpacity,
      }),
    )

    // --- the land ---------------------------------------------------------
    if (this.continents === "fill") this.landHolon = this.add(this.buildFilledLand())
    else this.landHolon = this.add(this.buildOutlinedLand())

    // --- the graticule ----------------------------------------------------
    this.grid = this.add(new Group({ members: this.graticule.value ? this.buildGraticule() : [] }))

    // --- the limb ring, on top -------------------------------------------
    this.limb = this.add(
      new Circle({ radius: this.radius, tint: this.limbTint, stroke: this.limbStroke }),
    )
  }

  /**
   * FILLED continents: one CLOSED, limb-clamped Line per coastline ring, all
   * children of one Stroke whose `fillOpacity` floods them under the even-odd
   * rule (the Sketch/FlowerText pattern — the host triangulates a parent whose
   * children are all closed Lines, so concave coastlines and interior lakes
   * come out right). Points are DERIVED from `spin` so the fill re-triangulates
   * as the globe turns.
   */
  private buildFilledLand(): Stroke {
    const parent = new Stroke({
      tint: this.land,
      stroke: scalar(0), // land reads as fill; no coastline stroke in fill mode
      fillOpacity: this.landOpacity,
    })
    for (const ring of continentRings) {
      const line = new Line({ tint: this.land, stroke: scalar(0) })
      deriveRing(line, this, () => {
        const pts = clampedRing(ring, this.radius.value, this.spin.value, this.tilt.value)
        return closeLoop(pts)
      })
      parentAdd(parent, line)
    }
    return parent
  }

  /**
   * OUTLINED continents: each ring's NEAR-FACE arcs as open coastline strokes
   * (shot 13). The far half is dropped rather than clamped, so no ghost lines
   * rake across the sphere. One Line per arc; all derived from `spin`.
   */
  private buildOutlinedLand(): Stroke {
    const parent = new Stroke({ tint: this.land, stroke: this.coastStroke, fillOpacity: scalar(0) })
    // A ring can split into a variable number of arcs as it crosses the limb,
    // but a holon's part set is fixed after compose(). So each ring gets a
    // FIXED pool of Line slots (a coastline rarely shows more than a few arcs
    // at once); unused slots derive to empty and draw nothing.
    const SLOTS = 4
    for (const ring of continentRings) {
      for (let s = 0; s < SLOTS; s++) {
        const line = new Line({ tint: this.land, stroke: this.coastStroke })
        deriveRing(line, this, () => {
          const arcs = frontArcs(ring, this.radius.value, this.spin.value, this.tilt.value)
          const arc = arcs[s]
          return arc ? arc.map((p) => ({ x: p.x, y: p.y, z: 0 })) : []
        })
        parentAdd(parent, line)
      }
    }
    return parent
  }

  /** Faint meridians and parallels, projected and near-face-clipped like the
   *  coastlines — a bare graticule for a globe that wants "sphere" without
   *  full continents (the option the task raised). */
  private buildGraticule(): Line[] {
    const lines: Line[] = []
    const nMer = Math.max(1, Math.round(this.meridians.value))
    const nPar = Math.max(1, Math.round(this.parallels.value))
    // Meridians: rings of constant longitude, pole to pole.
    for (let m = 0; m < nMer; m++) {
      const lon = -180 + (360 * m) / nMer
      const ring: number[] = []
      for (let lat = -90; lat <= 90; lat += 5) ring.push(lon, lat)
      lines.push(...this.graticuleArcs(ring))
    }
    // Parallels: rings of constant latitude.
    for (let p = 1; p < nPar; p++) {
      const lat = -90 + (180 * p) / nPar
      const ring: number[] = []
      for (let lon = -180; lon <= 180; lon += 5) ring.push(lon, lat)
      lines.push(...this.graticuleArcs(ring))
    }
    return lines
  }

  private graticuleArcs(ring: number[]): Line[] {
    const SLOTS = 2
    const out: Line[] = []
    for (let s = 0; s < SLOTS; s++) {
      const line = new Line({ tint: this.graticuleTint, stroke: this.coastStroke.times(0.5) })
      deriveRing(line, this, () => {
        const arcs = frontArcs(ring, this.radius.value, this.spin.value, this.tilt.value)
        const arc = arcs[s]
        return arc ? arc.map((p) => ({ x: p.x, y: p.y, z: 0 })) : []
      })
      out.push(line)
    }
    return out
  }
}

/** Close an open loop by repeating its first point — what a fill needs. */
const closeLoop = (pts: { x: number; y: number }[]): Vec3Like[] => {
  if (pts.length < 3) return []
  const out: Vec3Like[] = pts.map((p) => ({ x: p.x, y: p.y, z: 0 }))
  const a = out[0]!
  const b = out[out.length - 1]!
  if (Math.hypot(a.x - b.x, a.y - b.y) > 1e-6) out.push({ x: a.x, y: a.y, z: 0 })
  return out
}

/**
 * Add a Line as a child of a Stroke that has already been constructed. A
 * Stroke's parts are normally declared fields; these are built in a loop, so
 * they go through the same dynamic-part path compose() uses — the Group
 * members pattern, reached via the Stroke's own `add`. Exposed as a helper
 * because `add` is protected.
 */
const parentAdd = (parent: Stroke, child: Line): void => {
  ;(parent as unknown as { add(h: Line): Line }).add(child)
}

/**
 * Give a Line derived `points` recomputed whenever the Globe's `spin` (or
 * radius/tilt) changes, bumping `geomVersion` so the host's O(1) dirty-check
 * regenerates the ribbon and re-triangulates the fill. The same memo pattern
 * FourierTrace uses for its ink — written the same way deliberately: the key
 * is the source scalars, and `geomVersion` bumps on every recompute.
 */
const deriveRing = (line: Line, globe: Globe, compute: () => Vec3Like[]): void => {
  let key: readonly number[] | undefined
  let memo: Vec3Like[] = []
  Object.defineProperty(line, "points", {
    configurable: true,
    enumerable: true,
    get() {
      const next = [globe.spin.value, globe.radius.value, globe.tilt.value]
      if (!key || next.some((v, i) => v !== key![i])) {
        key = next
        memo = compute()
        line.geomVersion++
      }
      return memo
    },
    set(_v) {},
  })
}
