/**
 * Generate vocabulary/Globe/continents.ts — the coastline contours the Globe
 * wraps onto its sphere.
 *
 *   bun scripts/gen-globe-continents.ts <path-to-ne_110m_land.geojson>
 *
 * WHY REAL CARTOGRAPHIC DATA, NOT INVENTED SHAPES
 *
 * The globe recurs in four shots of the Liminal Consulting Web3 video and has
 * to READ as the world — Australia recognisable in shot 1, Africa/Europe in
 * the hero (shot 15). A graticule alone (see the design note in Globe.ts)
 * would read as "a sphere" but not as "the Earth", and hand-tracing continents
 * from 1280px frames would invent geography badly. So the coastlines are
 * Natural Earth's `ne_110m_land` (public domain, 1:110m — the coarsest
 * standard land layer), the SAME source every low-detail globe uses. That is
 * the least-invented convincing option: not a single coordinate is guessed.
 *
 * WHAT THIS DOES
 *
 *   - keeps only landmasses whose lon×lat bounding box spans more than
 *     MIN_SPAN square degrees, dropping the hundreds of speck-islands 110m
 *     still carries (they render as noise at globe scale, not as coastline);
 *   - simplifies each kept ring with Ramer–Douglas–Peucker at EPS degrees, so
 *     a continent that arrives with 400 vertices leaves with ~80 — enough to
 *     read, few enough that projecting + back-face-clipping them every frame
 *     for a spinning globe stays cheap;
 *   - stores each ring as flat [lon, lat, lon, lat, …] in DEGREES. The Globe
 *     turns lon/lat into sphere points, rotates by `spin`, and orthographically
 *     projects — so the DATA is projection-free and one dataset serves every
 *     face and every rotation.
 *
 * Rings are just closed coastlines; the Globe fills them under the even-odd
 * rule (a lake inside a continent would fall out for free), exactly as
 * FlowerText's mask and Sketch's drawings do.
 */

import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const here = dirname(fileURLToPath(import.meta.url))
const core = join(here, "..")

const src = process.argv[2]
if (!src) {
  console.error("usage: bun scripts/gen-globe-continents.ts <ne_110m_land.geojson>")
  process.exit(1)
}

/** Bounding-box span (in square degrees) below which a landmass is dropped. */
const MIN_SPAN = 40
/** Ramer–Douglas–Peucker tolerance, in degrees. */
const EPS = 0.7

type Pt = [number, number]

/** Perpendicular distance of p from the segment a→b, in degrees. */
const perpDist = (p: Pt, a: Pt, b: Pt): number => {
  const dx = b[0] - a[0]
  const dy = b[1] - a[1]
  const len = Math.hypot(dx, dy)
  if (len < 1e-12) return Math.hypot(p[0] - a[0], p[1] - a[1])
  const t = ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (len * len)
  const cx = a[0] + t * dx
  const cy = a[1] + t * dy
  return Math.hypot(p[0] - cx, p[1] - cy)
}

/** Ramer–Douglas–Peucker on an open polyline. */
const rdp = (pts: Pt[], eps: number): Pt[] => {
  if (pts.length < 3) return pts.slice()
  let maxD = 0
  let idx = 0
  const a = pts[0]!
  const b = pts[pts.length - 1]!
  for (let i = 1; i < pts.length - 1; i++) {
    const d = perpDist(pts[i]!, a, b)
    if (d > maxD) {
      maxD = d
      idx = i
    }
  }
  if (maxD <= eps) return [a, b]
  const left = rdp(pts.slice(0, idx + 1), eps)
  const right = rdp(pts.slice(idx), eps)
  return left.slice(0, -1).concat(right)
}

const spanOf = (ring: Pt[]): number => {
  let minx = Infinity
  let maxx = -Infinity
  let miny = Infinity
  let maxy = -Infinity
  for (const [x, y] of ring) {
    if (x < minx) minx = x
    if (x > maxx) maxx = x
    if (y < miny) miny = y
    if (y > maxy) maxy = y
  }
  return (maxx - minx) * (maxy - miny)
}

const geo = JSON.parse(readFileSync(src, "utf8")) as {
  features: { geometry: { type: string; coordinates: number[][][] | number[][][][] } }[]
}

const rings: number[][] = [] // each: flat [lon,lat,...]
for (const f of geo.features) {
  const g = f.geometry
  const polys = (g.type === "Polygon" ? [g.coordinates] : g.coordinates) as number[][][][]
  for (const poly of polys) {
    // poly[0] is the outer ring; inner rings (holes/lakes) are kept too, so
    // the even-odd fill carves them.
    for (const ring of poly) {
      const pts = ring.map((c) => [c[0]!, c[1]!] as Pt)
      if (spanOf(pts) < MIN_SPAN) continue
      const simplified = rdp(pts, EPS)
      // Ensure closed (RDP keeps first and last; the source ring is closed).
      const flat: number[] = []
      for (const [x, y] of simplified) flat.push(round(x), round(y))
      if (flat.length >= 6) rings.push(flat)
    }
  }
}

function round(v: number): number {
  return Math.round(v * 100) / 100
}

const totalPts = rings.reduce((n, r) => n + r.length / 2, 0)

const header = `/**
 * Coastline contours for the Globe — GENERATED by
 * scripts/gen-globe-continents.ts. Do not edit.
 *
 * Natural Earth ne_110m_land (public domain, 1:110m), the major landmasses
 * only (bbox span > ${MIN_SPAN} deg^2), each ring simplified with RDP at ${EPS} deg.
 * Rings are flat [lon, lat, lon, lat, …] in DEGREES; the Globe projects them
 * onto its sphere at render time (Globe.ts). ${rings.length} rings, ${totalPts} points.
 */

/** One coastline ring as flat [lon, lat, …] pairs, degrees. */
export const continentRings: readonly (readonly number[])[] = `

writeFileSync(
  join(core, "vocabulary/Globe/continents.ts"),
  header + JSON.stringify(rings) + "\n",
)

console.log(
  `wrote vocabulary/Globe/continents.ts — ${rings.length} rings, ${totalPts} points`,
)
