/**
 * Generate demo/web3/web3-mask.ts — the "Web3" glyph outlines FlowerText
 * packs its circles into.
 *
 *   bun scripts/gen-web3-mask.ts
 *
 * Shapes "Web3" with the bundled Arimo (demo/fonts/Arimo-Regular.ttf) via
 * harfbuzz, extracts each shaped glyph's outline, flattens the curves to
 * polygons with the repo's own SVG path flattener, and offsets each glyph by
 * its shaping advance. The result is committed as a TS module so the demo
 * needs no async font shaper at compose() time — glyph shaping is
 * asynchronous and a holon composes synchronously, so the mask is baked here
 * once. Letter counters (the holes in e, b, 3) come out as separate subpaths
 * and are carved by the even-odd mask test in src/geometry/flower.ts.
 */

import hbjsPromise from "harfbuzzjs/index.js"
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { parsePathData } from "../src/geometry/svg"

const here = dirname(fileURLToPath(import.meta.url))
const core = join(here, "..")

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const hb: any = await hbjsPromise

const fontBytes = readFileSync(join(core, "demo/fonts/Arimo-Regular.ttf"))
const blob = hb.createBlob(fontBytes)
const face = hb.createFace(blob, 0)
const font = hb.createFont(face)

const buffer = hb.createBuffer()
buffer.addText("Web3")
buffer.guessSegmentProperties()
hb.shape(font, buffer)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const glyphs: any[] = buffer.json()

// Harfbuzz draws outlines in font design units, y UP — the same sense as our
// plane — so no y-flip. Advances are in the same units; lay glyphs along x.
let penX = 0
const polygons: { x: number; y: number }[][] = []

for (const g of glyphs) {
  const d: string = font.glyphToPath(g.g)
  if (d && d.length > 1) {
    // Tolerance in font units (~upem/256) — well under a rendered pixel once
    // the mask is scaled down to scene units.
    for (const sp of parsePathData(d, 8)) {
      polygons.push(sp.points.map((p) => ({ x: p.x + penX + g.dx, y: p.y + g.dy })))
    }
  }
  penX += g.ax
}

let minX = Infinity
let minY = Infinity
let maxX = -Infinity
let maxY = -Infinity
for (const poly of polygons)
  for (const p of poly) {
    minX = Math.min(minX, p.x)
    minY = Math.min(minY, p.y)
    maxX = Math.max(maxX, p.x)
    maxY = Math.max(maxY, p.y)
  }

const header = `/**
 * "Web3" glyph outlines — GENERATED by scripts/gen-web3-mask.ts. Do not edit.
 *
 * The real Arimo (demo/fonts/Arimo-Regular.ttf) outlines of the word, shaped
 * with harfbuzz and flattened to polygons in font design units (y up). Letter
 * counters (the holes in e, b, 3) are separate subpaths, so the even-odd mask
 * test in src/geometry/flower.ts carves them. FlowerTextDemo centres and
 * scales these to scene units.
 */

export interface MaskPoint { x: number; y: number }
export interface MaskData {
  polygons: MaskPoint[][]
  bounds: { minX: number; minY: number; maxX: number; maxY: number }
}

export const web3MaskData: MaskData = `

writeFileSync(
  join(core, "demo/web3/web3-mask.ts"),
  header + JSON.stringify({ polygons, bounds: { minX, minY, maxX, maxY } }) + "\n",
)

console.log(
  `wrote demo/web3/web3-mask.ts — ${glyphs.length} glyphs, ${polygons.length} subpaths, ` +
    `bounds ${(maxX - minX).toFixed(0)}×${(maxY - minY).toFixed(0)}`,
)
