/**
 * svg2ts — convert an .svg into a checked-in TypeScript data module.
 *
 *   bun core/scripts/svg2ts.ts refs/pitch/svg-assets/svg/david.svg
 *   bun core/scripts/svg2ts.ts --all
 *
 * Why a build step and not a fetch: the framework runs in a browser,
 * which cannot read a file off disk, and the geometry never changes —
 * these are 2021 assets, frozen. Flattening them once at author time and
 * committing the result makes the polylines part of the source the way
 * every other construction is: reviewable, diffable, and identical on
 * every machine. A scene then writes `import { david } from
 * ".../assets/david"` and gets plain numbers, with no loader, no async,
 * and no network in the render path.
 *
 * The output is deterministic — same input file, byte-identical module —
 * so re-running this is a no-op unless the source or the flattener
 * changed, and the header records the source path and its SHA-256 so a
 * drifted asset is visible in a diff.
 *
 * Coordinates are emitted in the SVG's own units, centered on the origin
 * and y-flipped, with NO scaling: `height` is a Sketch parameter, and
 * baking one into the data would freeze a scene-level decision into an
 * asset.
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs"
import { createHash } from "node:crypto"
import { basename, join, resolve } from "node:path"
import { importSvg } from "../src/geometry/svg"

const REPO = resolve(import.meta.dir, "../..")
const SVG_DIR = join(REPO, "refs/pitch/svg-assets/svg")
const OUT_DIR = join(REPO, "core/vocabulary/Sketch/assets")

/** Decimal places kept per coordinate. */
const PRECISION = 3

/** snake_case / kebab-case file name → the camelCase export identifier. */
const identifierFor = (name: string): string =>
  name.replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase()).replace(/^[0-9]+/, "")

/** Trim trailing zeros so the module reads as numbers, not as noise. */
const fmt = (n: number): string => {
  const s = n.toFixed(PRECISION)
  const trimmed = s.replace(/\.?0+$/, "")
  return trimmed === "-0" || trimmed === "" ? "0" : trimmed
}

const convert = (svgPath: string): string => {
  const source = readFileSync(svgPath, "utf8")
  const hash = createHash("sha256").update(source).digest("hex").slice(0, 16)
  const name = basename(svgPath, ".svg")
  const id = identifierFor(name)
  const geo = importSvg(source, { height: null })

  const points = geo.subpaths.reduce((n, sp) => n + sp.length, 0)
  const lines: string[] = []
  lines.push("/**")
  lines.push(` * ${name} — generated by core/scripts/svg2ts.ts. Do not edit by hand.`)
  lines.push(" *")
  lines.push(` * Source: refs/pitch/svg-assets/svg/${name}.svg`)
  lines.push(` * SHA-256 (first 16): ${hash}`)
  lines.push(` * ${geo.subpaths.length} subpaths, ${points} points, centered, y-flipped,`)
  lines.push(" * in the SVG's own units (scale to a height via the Sketch's `height`).")
  if (geo.skipped.length > 0) {
    lines.push(` * Skipped element types: ${geo.skipped.join(", ")}`)
  }
  lines.push(" */")
  lines.push("")
  lines.push('import type { SketchData } from "../data"')
  lines.push("")
  lines.push(`export const ${id}: SketchData = {`)
  lines.push(`  name: ${JSON.stringify(name)},`)
  lines.push(`  source: ${JSON.stringify(`refs/pitch/svg-assets/svg/${name}.svg`)},`)
  lines.push(`  hash: ${JSON.stringify(hash)},`)
  lines.push("  subpaths: [")
  for (const sp of geo.subpaths) {
    lines.push(`    [${sp.map((p) => `${fmt(p.x)},${fmt(p.y)}`).join(", ")}],`)
  }
  lines.push("  ],")
  lines.push(`  closed: [${geo.closedFlags.map((c) => (c ? "1" : "0")).join(",")}],`)
  lines.push("}")
  lines.push("")

  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })
  const outPath = join(OUT_DIR, `${name}.ts`)
  writeFileSync(outPath, lines.join("\n"))
  const kb = (lines.join("\n").length / 1024).toFixed(0)
  console.log(
    `${name.padEnd(20)} ${String(geo.subpaths.length).padStart(4)} subpaths` +
      ` ${String(points).padStart(7)} points  ${kb.padStart(5)} KB` +
      (geo.skipped.length ? `  (skipped: ${geo.skipped.join(",")})` : ""),
  )
  return name
}

const args = process.argv.slice(2)
if (args.length === 0) {
  console.error("usage: bun core/scripts/svg2ts.ts <file.svg…> | --all")
  process.exit(1)
}

const files =
  args[0] === "--all"
    ? readdirSync(SVG_DIR)
        .filter((f) => f.endsWith(".svg"))
        .sort()
        .map((f) => join(SVG_DIR, f))
    : args.map((a) => resolve(a))

const names = files.map(convert)

// The barrel: one import site for scenes that want to browse the corpus.
const index: string[] = [
  "/**",
  " * The 2021 SVG asset corpus — generated by core/scripts/svg2ts.ts.",
  " * Do not edit by hand.",
  " *",
  " * These are the drawings the Origins video was made from, recovered",
  " * from the C4D preferences folder they lived in outside version",
  " * control (docs/reports/origins-vocabulary.md §4).",
  " */",
  "",
  ...names.map((n) => `export { ${identifierFor(n)} } from "./${n}"`),
  "",
]
writeFileSync(join(OUT_DIR, "index.ts"), index.join("\n"))
console.log(`\n${names.length} asset module(s) + index.ts written to ${OUT_DIR}`)
